version: '3.8'
services:
  postgres:
    image: postgres:13.3
    container_name: pg-db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql1/data
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h ${DB_HOST}
      interval: 30s
      timeout: 60s
      retries: 5

volumes:
  pg-data:
    name: pg-db-data
